#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Andreas Nissen
# SPDX-License-Identifier: Apache-2.0
"""Render the readable evaluation cases from the case set. The JSON file is the source."""
import argparse
import json
from pathlib import Path
import sys

HEADER = """<!-- SPDX-FileCopyrightText: 2026 Andreas Nissen -->
<!-- SPDX-License-Identifier: Apache-2.0 -->

# Evaluation cases

Generated from [cases.json](cases.json) by `scripts/render_cases.py`. Do not edit this file by
hand: the reporter digests the JSON, so a change made only here would leave recorded runs
validating against instructions nobody evaluated. Change `cases.json` and render again.

Read [evaluation.md](../references/evaluation.md) first: it covers when to run these, how to
record a run, and what the results do and do not establish.

These cases are part of this bundle and carry its licensing: Copyright 2026 Andreas Nissen,
Apache-2.0. See the bundle [NOTICE](../NOTICE). `cases.json` has no comment syntax and carries
its notice here.

Run a case by giving its prompt to the host under test with the skill selected, in the starting
state the case names. Record what the agent did against every line under **Expected**.
"""


def render(document):
    lines = [HEADER, "## Disqualifiers", ""]
    lines.append("**Every disqualifier applies to every case.** Any one of them fails the case it appears")
    lines.append("in, however good the rest of the output looks. Each case also names the ones its own shape")
    lines.append("most invites, under **Watch for** — that is where to look first, not a limit on what counts.")
    lines.append("")
    for name, description in document["disqualifiers"].items():
        lines.append(f"- `{name}` — {description}")
    lines.append("")
    lines.append("## Starting states")
    lines.append("")
    lines.append("A case that needs a repository names the fixture state to build with")
    lines.append("`scripts/make_fixture.py`, so every evaluator starts from the same bytes. A case whose")
    lines.append("starting point is an empty directory or a chat window names no fixture.")
    lines.append("")
    for name, description in document["fixtures"].items():
        lines.append(f"- `{name}` — {description}")
    lines.append("")
    lines.append("## Cases")
    lines.append("")
    for case in document["cases"]:
        lines.append(f"### `{case['id']}`")
        lines.append("")
        lines.append(f"Starting point: {case['starting_point']}.")
        if case["fixture"]:
            lines.append("")
            lines.append(f"```sh\npython3 skills/ai-sdlc-skill/scripts/make_fixture.py --state {case['fixture']} --into <throwaway path>\n```")
        lines.append("")
        lines.append("> " + case["prompt"])
        lines.append("")
        lines.append("**Expected**")
        lines.append("")
        for behavior in case["expected"]:
            lines.append(f"- {behavior}")
        lines.append("")
        lines.append("Watch for: " + ", ".join(f"`{flag}`" for flag in case["watch_for"]) + ".")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cases", default=str(Path(__file__).resolve().parents[1] / "evals" / "cases.json"))
    parser.add_argument("--out", default=str(Path(__file__).resolve().parents[1] / "evals" / "cases.md"))
    parser.add_argument("--check", action="store_true", help="verify the rendered file is current, changing nothing")
    args = parser.parse_args(argv)
    rendered = render(json.loads(Path(args.cases).read_text()))
    if args.check:
        current = Path(args.out).read_text() if Path(args.out).is_file() else ""
        if current != rendered:
            print("cases.md is not the rendering of cases.json; run scripts/render_cases.py")
            return 1
        print("cases.md matches cases.json")
        return 0
    Path(args.out).write_text(rendered)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
